from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 239)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.labels = list()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labels.append(QtWidgets.QLabel(self.centralwidget))
        self.labels[0].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labels[0].setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labels[0].setTextFormat(QtCore.Qt.RichText)
        self.labels[0].setAlignment(QtCore.Qt.AlignCenter)
        self.labels[0].setObjectName("label")
        self.horizontalLayout.addWidget(self.labels[0])
        self.labels.append(QtWidgets.QLabel(self.centralwidget))
        self.labels[1].setAlignment(QtCore.Qt.AlignCenter)
        self.labels[1].setObjectName("label_2")
        self.horizontalLayout.addWidget(self.labels[1])
        self.labels.append(QtWidgets.QLabel(self.centralwidget))
        self.labels[2].setAlignment(QtCore.Qt.AlignCenter)
        self.labels[2].setObjectName("label_3")
        self.horizontalLayout.addWidget(self.labels[2])
        self.labels.append(QtWidgets.QLabel(self.centralwidget))
        self.labels[3].setAlignment(QtCore.Qt.AlignCenter)
        self.labels[3].setObjectName("label_4")
        self.horizontalLayout.addWidget(self.labels[3])
        self.labels.append(QtWidgets.QLabel(self.centralwidget))
        self.labels[4].setAlignment(QtCore.Qt.AlignCenter)
        self.labels[4].setObjectName("label_5")
        self.horizontalLayout.addWidget(self.labels[4])
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Equalizer = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Equalizer.sizePolicy().hasHeightForWidth())
        self.Equalizer.setSizePolicy(sizePolicy)
        self.Equalizer.setObjectName("Equalizer")
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Equalizer Test"))
        self.labels[0].setText(_translate("MainWindow", "0"))
        self.labels[1].setText(_translate("MainWindow", "0"))
        self.labels[2].setText(_translate("MainWindow", "0"))
        self.labels[3].setText(_translate("MainWindow", "0"))
        self.labels[4].setText(_translate("MainWindow", "0"))
        self.Equalizer.setText(_translate("MainWindow", "Equalizer"))
